#!/bin/sh

case "$1" in
    configure|upgrade)
        [ ! -f /etc/default/dh_gitchangelog.conf ] ||
        { rm -f /etc/default/dh_gitchangelog.conf ; echo "remove old configuration file" ; }
    ;;
    abort-upgrade|abort-remove|abort-deconfigure) ;;
    *)
        echo "Unrecognized argument: $1" ; exit 1
    ;;
esac
